/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      constant: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      constant: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      constant: true
    }
  },
  {
    name: 'entry',
    path: '/entry',
    component: 'layout.base$view.entry',
    meta: {
      title: 'entry',
      constant: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      constant: true
    }
  },
  {
    name: 'tableBuilder',
    path: '/tableBuilder',
    component: 'layout.base',
    meta: {
      title: 'tableBuilder',
      roles: ['1'],
      id: '1',
      icon: 'ri:table-fill'
    },
    children: [
      {
        name: 'tableBuilder_builder',
        path: '/tableBuilder/builder',
        component: 'view.tableBuilder_builder',
        meta: {
          title: 'tableBuilder_builder',
          roles: ['3'],
          id: '3'
        }
      },
      {
        name: 'tableBuilder_list',
        path: '/tableBuilder/list',
        component: 'view.tableBuilder_list',
        meta: {
          title: 'tableBuilder_list',
          roles: ['2'],
          id: '2'
        }
      }
    ]
  },
  {
    name: 'test',
    path: '/test',
    component: 'layout.base$view.test',
    meta: {
      title: 'test',
      constant: true
    }
  }
];
