/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      constant: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      constant: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      constant: true
    }
  },
  {
    name: 'builder',
    path: '/builder',
    component: 'layout.base$view.builder',
    meta: {
      title: 'builder',
      roles: ['5201'],
      id: '5201',
      icon: 'fluent:person-settings-20-filled'
    }
  },
  {
    name: 'entry',
    path: '/entry',
    component: 'layout.base$view.entry',
    meta: {
      title: 'entry',
      constant: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      constant: true
    }
  }
];
